# Generated by Django 4.1.7 on 2023-05-23 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriaLeczenia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('opis_problemu_zdrowotnego', models.CharField(max_length=255)),
                ('zalecone_leczenie', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lekarz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=20)),
                ('nazwisko', models.CharField(max_length=50)),
                ('specjalizacja', models.CharField(max_length=50)),
                ('dane_kontaktowe', models.TextField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pensjonariusz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=20)),
                ('nazwisko', models.CharField(max_length=50)),
                ('data_urodzenia', models.DateField()),
                ('plec', models.CharField(max_length=10)),
                ('dane_kontaktowe', models.TextField(max_length=50, null=True)),
                ('informacje_medyczne', models.CharField(max_length=255)),
                ('historia_leczenia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pensjonariusze', to='dom.historialeczenia')),
                ('lekarze', models.ManyToManyField(to='dom.lekarz')),
            ],
        ),
        migrations.CreateModel(
            name='Personel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=20)),
                ('nazwisko', models.CharField(max_length=50)),
                ('stanowisko', models.CharField(max_length=50, null=True)),
                ('data_zatrudnienia', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Recepty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_wystawienia', models.DateField()),
                ('zalecane_leki', models.TextField(max_length=255, null=True)),
                ('lekarz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dom.lekarz')),
                ('pensjonariusz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dom.pensjonariusz')),
            ],
        ),
        migrations.CreateModel(
            name='Pielegniarz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=20)),
                ('nazwisko', models.CharField(max_length=50)),
                ('pracownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dom.personel')),
            ],
        ),
        migrations.AddField(
            model_name='pensjonariusz',
            name='pielegniarki',
            field=models.ManyToManyField(to='dom.pielegniarz'),
        ),
        migrations.AddField(
            model_name='lekarz',
            name='pracownik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dom.personel'),
        ),
        migrations.AddField(
            model_name='historialeczenia',
            name='pensjonariusz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historie_leczenia', to='dom.pensjonariusz'),
        ),
        migrations.AddField(
            model_name='historialeczenia',
            name='recepta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dom.recepty'),
        ),
    ]
