# Generated by Django 4.1.7 on 2023-05-23 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dom', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pielegniarz',
            name='pracownik',
        ),
        migrations.RemoveField(
            model_name='lekarz',
            name='pracownik',
        ),
        migrations.RemoveField(
            model_name='pensjonariusz',
            name='pielegniarki',
        ),
        migrations.DeleteModel(
            name='Personel',
        ),
        migrations.DeleteModel(
            name='Pielegniarz',
        ),
    ]
